[package]
name = "foundry-evm"
description = "Main Foundry EVM backend abstractions"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
foundry-cheatcodes = { workspace = true, optional = true }
foundry-common = { workspace = true, optional = true }
foundry-compilers = { workspace = true, optional = true }
foundry-config = { workspace = true, optional = true }
foundry-evm-core.workspace = true
foundry-evm-coverage = { workspace = true, optional = true }
foundry-evm-fuzz = { workspace = true, optional = true }
foundry-evm-sancov = { workspace = true, optional = true }
foundry-evm-hardforks.workspace = true
foundry-evm-networks = { workspace = true, optional = true }
foundry-evm-traces.workspace = true

alloy-dyn-abi = { workspace = true, optional = true, features = ["arbitrary", "eip712"] }
alloy-consensus.workspace = true
alloy-eips = { workspace = true, optional = true }
alloy-evm = { workspace = true, optional = true }
alloy-json-abi = { workspace = true, optional = true }
alloy-primitives = { workspace = true, features = [
    "serde",
    "getrandom",
    "arbitrary",
    "rlp",
] }
alloy-rpc-types = { workspace = true, features = ["trace"] }
alloy-sol-types = { workspace = true, optional = true }
revm = { workspace = true, optional = true, default-features = false, features = [
    "std",
    "serde",
    "memory_limit",
    "optional_eip3607",
    "optional_eip7623",
    "optional_block_gas_limit",
    "optional_no_base_fee",
    "arbitrary",
    "c-kzg",
] }
revm-inspectors = { workspace = true, optional = true }
tempo-precompiles = { workspace = true, optional = true }
tempo-primitives = { workspace = true, optional = true }

eyre.workspace = true
evm2.workspace = true
parking_lot = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
indicatif = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
foundry-cheatcodes.workspace = true
alloy-sol-types.workspace = true

[features]
default = ["optimism", "revm"]
revm = [
    "foundry-evm-coverage/revm",
    "foundry-evm-fuzz/revm",
    "dep:tracing",
    "dep:alloy-sol-types",
    "dep:foundry-cheatcodes",
    "dep:foundry-common",
    "dep:foundry-compilers",
    "dep:foundry-config",
    "dep:foundry-evm-coverage",
    "dep:foundry-evm-fuzz",
    "dep:foundry-evm-sancov",
    "dep:foundry-evm-networks",
    "dep:alloy-dyn-abi",
    "dep:alloy-eips",
    "dep:alloy-evm",
    "dep:alloy-json-abi",
    "dep:revm",
    "dep:revm-inspectors",
    "dep:tempo-precompiles",
    "dep:tempo-primitives",
    "dep:parking_lot",
    "dep:proptest",
    "dep:rand",
    "dep:thiserror",
    "dep:indicatif",
    "dep:serde_json",
    "dep:serde",
    "dep:uuid",
    "dep:rayon",
    "dep:tokio",
    "foundry-cheatcodes/revm",
    "foundry-common/revm",
    "foundry-evm-core/revm",
    "foundry-evm-hardforks/revm",
    "foundry-evm-traces/revm",
]
monad = [
    "revm",
    "foundry-evm-core/monad",
    "foundry-evm-hardforks/monad",
    "foundry-evm-networks/monad",
    "foundry-cheatcodes/monad",
    "foundry-evm-coverage/monad",
    "foundry-evm-fuzz/monad",
    "foundry-evm-traces/monad",
]
base = [
    "revm",
    "foundry-cheatcodes/base",
    "foundry-common/base",
    "foundry-config/base",
    "foundry-evm-core/base",
    "foundry-evm-coverage/base",
    "foundry-evm-fuzz/base",
    "foundry-evm-hardforks/base",
    "foundry-evm-networks/base",
    "foundry-evm-traces/base",
]
optimism = [
    "revm",
    "foundry-evm-core/optimism",
    "foundry-evm-hardforks/optimism",
    "foundry-evm-networks/optimism",
    "foundry-common/optimism",
    "foundry-cheatcodes/optimism",
    "foundry-evm-coverage/optimism",
    "foundry-evm-fuzz/optimism",
    "foundry-evm-traces/optimism",
]
